# Generated by Django 2.1.1 on 2018-09-20 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('client_email', models.CharField(max_length=50)),
                ('client_phone', models.IntegerField()),
                ('client_mobile', models.IntegerField()),
                ('client_account', models.CharField(max_length=50)),
                ('client_project', models.CharField(max_length=50)),
                ('client_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('emp_email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('empid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deptmaster',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.Employee')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
            ],
            bases=('web.employee',),
        ),
        migrations.CreateModel(
            name='Client_rate',
            fields=[
                ('deptmaster_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.Deptmaster')),
                ('client_score', models.IntegerField()),
            ],
            bases=('web.deptmaster',),
        ),
        migrations.CreateModel(
            name='Dept_rate',
            fields=[
                ('deptmaster_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.Deptmaster')),
                ('dept_score', models.IntegerField()),
            ],
            bases=('web.deptmaster',),
        ),
        migrations.CreateModel(
            name='Emp_rate',
            fields=[
                ('deptmaster_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.Deptmaster')),
                ('emp_score', models.IntegerField()),
            ],
            bases=('web.deptmaster',),
        ),
    ]
