# Generated by Django 2.1.1 on 2018-09-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=30, null=True)),
                ('client_last_name', models.CharField(max_length=30, null=True)),
                ('client_middle_name', models.CharField(max_length=30, null=True)),
                ('client_email', models.CharField(max_length=50, null=True)),
                ('client_phone', models.IntegerField(null=True)),
                ('client_mobile', models.IntegerField(null=True)),
                ('client_account', models.CharField(max_length=50, null=True)),
                ('client_project', models.CharField(max_length=50, null=True)),
                ('client_address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ratee', models.CharField(max_length=50, null=True)),
                ('client_score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dept_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_ratee', models.CharField(max_length=50, null=True)),
                ('dept_score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_ratee', models.CharField(max_length=50, null=True)),
                ('emp_score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('middle_name', models.CharField(max_length=30, null=True)),
                ('emp_email', models.CharField(max_length=50, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('empid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('logo', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
