# Generated by Django 2.1.1 on 2018-09-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Client_rate',
        ),
        migrations.DeleteModel(
            name='Dept_rate',
        ),
        migrations.DeleteModel(
            name='Emp_rate',
        ),
    ]
